using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Fale
{
    class InitialVar
    {

        public int ini_var_max_y = 6;
        public int ini_var_min_y = -6;
        public int ini_var_max_x = 1000;
        public int ini_var_szybkosc_wyswietlania = 950;
        public double ini_var_stosunek_v_ = 1;
        public int ini_var_bazowa_v = 300;
        public double ini_var_v_1 = 300;
        public double ini_var_minimum_v_1 = -10;
        public double ini_var_v_2 = 300;
        public double ini_var_minimum_v_2 = -10;
        public double ini_var_stosunek_a_ = 1;
        public int ini_var_bazowa_a = 1;
        public double ini_var_a_1 = 1;
        public double ini_var_a_2 = 1;
        public double ini_var_stosunek_f_ = 1;
        public double ini_var_bazowa_f = 15;
        public int ini_var_f_1 = 15;
        public int ini_var_f_2 = 15;
        public double ini_var_r_faz = 0;
        public double ini_var_faza_1 = 0;
        public double ini_var_faza_2 = 0;
        public int ini_var_wymiar_x = 700;
        public int ini_var_wymiar_y = 400;
        public int ini_var_krok = 15;
        public int ini_var_krok_t = 5;
        public double ini_var_gestosc = 5;
        public int ini_var_pkt = 1;
        public int ini_var_s_f1 = 500;
        public int ini_var_s_f2 = 500;
        public int ini_var_s_a1 = 500;
        public int ini_var_s_a2 = 500;
        public int ini_var_s_t = 1;
        public string ini_var_styl_1 = "Liniowy";
        public string ini_var_styl_2 = "Liniowy";
        public string ini_var_styl_3 = "Liniowy";

        public int var_max_y;
        public int var_min_y;
        public int var_max_x;
        public int var_szybkosc_wyswietlania;
        public double var_stosunek_v_;
        public int var_bazowa_v;
        public double var_v_1;
        public double var_minimum_v_1;
        public double var_v_2;
        public double var_minimum_v_2;
        public double var_stosunek_a_;
        public int var_bazowa_a;
        public double var_a_1;
        public double var_a_2;
        public double var_stosunek_f_;
        public double var_bazowa_f;
        public int var_f_1;
        public int var_f_2;
        public double var_r_faz;
        public double var_faza_1;
        public double var_faza_2;
        public int var_wymiar_x;
        public int var_wymiar_y;
        public int var_krok;
        public int var_krok_t;
        public double var_gestosc;
        public int var_pkt;
        public int var_s_f1;
        public int var_s_f2;
        public int var_s_a1;
        public int var_s_a2;
        public int var_s_t;
        public string var_styl_1;
        public string var_styl_2;
        public string var_styl_3;


        public int max_y = 1;
        public int min_y = -1;
        public int max_x = 1;
        public int szybkosc_wyswietlania = 1;
        public double stosunek_v_ = 0.1;
        public int bazowa_v = 80;
        public double v_1 = 80;
        public double minimum_v_1 = 80;
        public double v_2 = 80;
        public double minimum_v_2 = 80;
        public double stosunek_a_ = 0.1;
        public int bazowa_a = 1;
        public double a_1 = 0;
        public double a_2 = 0;
        public double stosunek_f_ = 0.1;
        public double bazowa_f = 1;
        public int f_1 = 1;
        public int f_2 = 1;
        public double r_faz = 0;
        public double faza_1 = 0;
        public double faza_2 = 0;
        public int wymiar_x = 1;
        public int wymiar_y = 1;
        public int krok = 1;
        public int krok_t = 1;
        public double gestosc = 1;
        public int pkt = 1;
        public int s_f1 = 100;
        public int s_f2 = 100;
        public int s_a1 = 200;
        public int s_a2 = 200;

        public int m_max_y = 100;
        public int m_min_y = -100;
        public int m_max_x = 10000;
        public int m_szybkosc_wyswietlania = 999;
        public double m_stosunek_v_ = 10;
        public int m_bazowa_v = 1000;
        public double m_v_1 = 1000;
        public double m_v_2 = 1000;
        public double m_stosunek_a_ = 10;
        public int m_bazowa_a = 600;
        public double m_a_1 = 100;
        public double m_a_2 = 100;
        public double m_stosunek_f_ = 10;
        public double m_bazowa_f = 100;
        public int m_f_1 = 10000;
        public int m_f_2 = 10000;
        public double m_r_faz = 360;
        public double m_faza_1 = 360;
        public double m_faza_2 = 360;
        public int m_wymiar_x = Screen.PrimaryScreen.Bounds.Width;
        public int m_wymiar_y = Screen.PrimaryScreen.Bounds.Height;
        public int m_krok = 360;
        public int m_krok_t = 1000;
        public double m_gestosc = 200;
        public int m_pkt = 5;
        public int m_s_f1 = 10000;
        public int m_s_f2 = 10000;
        public int m_s_a1 = 10000;
        public int m_s_a2 = 10000;

        public bool status = false;
        public bool ok = true;

        public bool ini_w_f_1 = true;
        public bool ini_w_f_2 = true;
        public bool ini_w_f_w = true;
        public bool ini_s_v = false;
        public bool ini_s_a = false;
        public bool ini_s_f = false;
        public bool ini_z_c = true;
        public bool ini_r_m = false;
        public bool ini_r_s = true;
        public bool ini_r_d = false;
        public bool ini_r_s_w = false;
        public bool ini_r_s_s = true;
        public bool ini_r_s_sz = false;
        public bool ini_c_pkt = false;
        public bool ini_s_pkt_f1 = true;
        public bool ini_s_pkt_f2 = false;
        public bool ini_s_pkt_wypadkowa = false;
        public bool ini_c_left1 = false;
        public bool ini_c_right1 = true;
        public bool ini_c_left2 = false;
        public bool ini_c_right2 = true;
        public bool ini_s_ch_stereo = true;
        public bool ini_s_w2 = true;
        public bool ini_sound = false;

        public bool w_f_1;
        public bool w_f_2;
        public bool w_f_w;
        public bool s_v;
        public bool s_a;
        public bool s_f;
        public bool z_c;
        public bool r_m;
        public bool r_s;
        public bool r_d;
        public bool r_s_w;
        public bool r_s_s;
        public bool r_s_sz;
        public bool c_pkt;
        public bool s_pkt_f1;
        public bool s_pkt_f2;
        public bool s_pkt_wypadkowa;
        public bool c_left1;
        public bool c_right1;
        public bool c_left2;
        public bool c_right2;
        public bool s_ch_stereo;
        public bool s_w2;
        public bool sound;
        public bool more = true;

        public double tmp1 = 0;
        public double tmp2 = 0;
        public double tmp = 0;
        public double t = 0;
        public float tmp_f = 0;
        public double y = 0;
        public double y2 = 0;
        public double tmp2_d = 0;
        public string tmp_s;
        public double n_tmp = 0;
        public int tmp_height = 0;
        public int tmp_screenX = 0;
        public int tmp_screenY = 0;

        public double v1 = 0;
        public double v2 = 0;
        public double f1 = 0;
        public double f2 = 0;
        public double a1 = 0;
        public double a2 = 0;
        public int active_pkt;
        public int i = 90;

        public InitialVar()
        {
            var_max_y = ini_var_max_y;
            var_min_y = ini_var_min_y;
            var_max_x = ini_var_max_x;
            var_szybkosc_wyswietlania = ini_var_szybkosc_wyswietlania;
            var_stosunek_v_ = ini_var_stosunek_v_;
            var_bazowa_v = ini_var_bazowa_v;
            var_v_1 = ini_var_v_1;
            var_minimum_v_1 = ini_var_minimum_v_1;
            var_v_2 = ini_var_v_2;
            var_minimum_v_2 = ini_var_minimum_v_2;
            var_stosunek_a_ = ini_var_stosunek_a_;
            var_bazowa_a = ini_var_bazowa_a;
            var_a_1 = ini_var_a_1;
            var_a_2 = ini_var_a_2;
            var_stosunek_f_ = ini_var_stosunek_f_;
            var_bazowa_f = ini_var_bazowa_f;
            var_f_1 = ini_var_f_1;
            var_f_2 = ini_var_f_2;
            var_r_faz = ini_var_r_faz;
            var_faza_1 = ini_var_faza_1;
            var_faza_2 = ini_var_faza_2;
            var_wymiar_x = ini_var_wymiar_x;
            var_wymiar_y = ini_var_wymiar_y;
            var_krok = ini_var_krok;
            var_krok_t = ini_var_krok_t;
            var_gestosc = ini_var_gestosc;
            var_pkt = ini_var_pkt;
            var_s_f1 = ini_var_s_f1;
            var_s_f2 = ini_var_s_f2;
            var_s_a1 = ini_var_s_a1;
            var_s_a2 = ini_var_s_a2;
            var_s_t = ini_var_s_t;
            var_styl_1 = ini_var_styl_1;
            var_styl_2 = ini_var_styl_2;
            var_styl_3 = ini_var_styl_3;

            w_f_1 = ini_w_f_1;
            w_f_2 = ini_w_f_2;
            w_f_w = ini_w_f_w;
            s_v = ini_s_v;
            s_a = ini_s_a;
            s_f = ini_s_f;
            z_c = ini_z_c;
            r_m = ini_r_m;
            r_s = ini_r_s;
            r_d = ini_r_d;
            r_s_w = ini_r_s_w;
            r_s_s = ini_r_s_s;
            r_s_sz = ini_r_s_sz;
            c_pkt = ini_c_pkt;
            s_pkt_f1 = ini_s_pkt_f1;
            s_pkt_f2 = ini_s_pkt_f2;
            s_pkt_wypadkowa = ini_s_pkt_wypadkowa;
            c_left1 = ini_c_left1;
            c_right1 = ini_c_right1;
            c_left2 = ini_c_left2;
            c_right2 = ini_c_right2;
            s_ch_stereo = ini_s_ch_stereo;
            s_w2 = ini_s_w2;
            sound = ini_sound;
        }
    }
}
